# Generated by Django 5.0 on 2023-12-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('times_used_in_games', models.IntegerField(default=0)),
                ('last_time_used_in_game', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('fact', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CountryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('times_used_in_games', models.IntegerField(default=0)),
                ('last_time_used_in_game', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('unsplash_id', models.CharField(max_length=20)),
                ('full_location_string', models.TextField()),
                ('full_URLs_list', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
