# Generated by Django 5.0 on 2023-12-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriviaGame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryphoto',
            name='unsplash_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
